### PR TITLE
Support for Android bundle files

### LINKED ISSUE #35: Support for App Bundles
Xamarin now supports [App Bundles](https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/app-bundles.md). We've changed our build system to generate a `.aab` rather than a `.apk` and then we started getting the following error on Bitrise in the archive step:

```
Legacy exporter failed to find apk in (/Users/vagrant/git/path)
No output generated
```

The weird part is that the `deploy to bitrise` step works normally and manages to find the `.aab` and attach it to the list of generated artifacts! The problem is simply that the Xamarin step is failing because it expects to find a  `.apk`.

Is using bundles not supported for Xamarin? If not, is it in the plans?

### PR DESCRIPTION
**Pull request by heytherewill**
## What's this?
This Pull Request makes the xamarin archive step not fail when archiving .aab files.
As mentioned in the issue this PR closes, everything else works (the Xamarin toolchain and the deploy to bitrise step) but we need this change so the archive steps passes (rather than failing with a false positive).

## Relationships
Depends on https://github.com/bitrise-io/go-xamarin/pull/49
Closes #35 

## How is it done?
This basically checks for the constant added in https://github.com/bitrise-io/go-xamarin/pull/49 and ensures that it can be uploaded. 

I'm really new to the whole bitrise steps thing, so bear with me if I forgot something important

### CODE REVIEW

**Comment by lszucs** [comment]
Hey there @heytherewill!

Sorry for spamming with notifications. I got totally confused among the opened tabs. 😿 

Back to business. Thanks for the PR! Can you please elaborate on how did you set this up on bitrise.io? Did you use a script step to build the `aab` file?

Based on the docs (https://docs.microsoft.com/en-us/xamarin/android/release-notes/9/9.4), exporting an actually deployable AAB has to be done using a command similar to this:

```
msbuild -restore AndroidApp.csproj ^
  -t:SignAndroidPackage ^
  -p:Configuration=Release ^
  -p:AndroidKeyStore=True ^
  -p:AndroidSigningKeyStore=com.contoso.keystore ^
  -p:AndroidSigningStorePass=password ^
  -p:AndroidSigningKeyAlias=keyAlias ^
  -p:AndroidSigningKeyPass=password
```



The reason I'm asking is, that we have the `PackageForAndroid` target hardcoded in the step, so currently, our expectation is, that this PR would not help with the `aab` export without modifying the related logic or introducing a new input. In fact, it wouldn't even output an `aab`.

Other than that, it looks good. 👌 👑   We just need to make sure we know if there is anything else, that needs to be added, before release. :)

**Comment by heytherewill** [comment]
> Can you please elaborate on how did you set this up on bitrise.io? 

We manually edited the `bitrise.yml` file to use our custom step. We also created a branch (github.com/toggl/steps-xamarin-archive) that properly targets the correct dependencies.

> Did you use a script step to build the aab file?

-ish. The changes for building an .aab are rather simple, and you can check them [here](https://github.com/toggl/mobileapp/pull/5832/files). The gist of it is setting `<AndroidPackageFormat>aab</AndroidPackageFormat>` in your csproj and you're good to go. 

However, we are using cake as our build system, so we do not use bitrise's build step, using a simple build script instead. I can't tell whether it'd work or not using the bitrise step 😅 

>  We just need to make sure we know if there is anything else, that needs to be added, before release

Other than https://github.com/bitrise-io/go-xamarin/pull/49 getting merged and then the dependencies here being updated, I think there's nothing else that needs to be done :)

**Comment by lszucs** [comment]
Hi @heytherewill!

Apologies for the late response. We will be happy to merge your PR, however, we will need to introduce changes to the step, to fully incorporate it. We currently have the build target hardcoded in the step, so the step will always output an APK, no matter what.

We created a story for this and will start with merging your changes, once we start working on it, so as to not have any half-finished feature on `master`.

Thanks very much for the contribution! 🥇

**Comment by seanrodda** [comment]
Hi @lszucs, any update on merging these changes to master?

**Comment by mateherber** [comment]
Hi @heytherewill,

As I wrote on the [go-xamarin](https://github.com/bitrise-io/go-xamarin/pull/49) PR (better late than never) we'd like to continue merging this contribution to the step.

When the other PR is merged a `dep update` has to be done on this branch and the changes are needed to be pushed. After that if CI passes we can proceed with merging.

**Comment by mateherber** [comment]
I'm closing this PR due to lack of activity. We'll utilize these pieces when implementing the `*.aab` support for the Xamarin Archive Step

**Pull request closed without merging**
